-- Approxense — Seed Questions (100 questions, 20 per category)
-- Run this in Supabase SQL Editor after 001_initial_schema.sql

INSERT INTO questions (category, question_text, answer, unit, language) VALUES

-- DISTANCE (20)
('distance', 'Dünya''nın çevresi kaç **km**''dir?', 40075, 'km', 'tr'),
('distance', 'Ay''a olan ortalama uzaklık kaç **km**''dir?', 384400, 'km', 'tr'),
('distance', 'İstanbul''dan Ankara''ya olan karayolu mesafesi kaç **km**''dir?', 454, 'km', 'tr'),
('distance', 'Everest Dağı''nın yüksekliği kaç **m**''dir?', 8849, 'm', 'tr'),
('distance', 'Atlantik Okyanusu''nun ortalama genişliği kaç **km**''dir?', 3332, 'km', 'tr'),
('distance', 'Amazon Nehri''nin uzunluğu kaç **km**''dir?', 6400, 'km', 'tr'),
('distance', 'Türkiye''nin kuzeyden güneye olan maksimum genişliği kaç **km**''dir?', 550, 'km', 'tr'),
('distance', 'Işığın bir saniyede aldığı yol kaç **km**''dir?', 300000, 'km', 'tr'),
('distance', 'Boğaz köprüsünün (1. köprü) uzunluğu kaç **m**''dir?', 1560, 'm', 'tr'),
('distance', 'Dünya''dan Güneş''e olan ortalama uzaklık kaç **km**''dir?', 149600000, 'km', 'tr'),
('distance', 'Bir insan saçının kalınlığı kaç **mikrometre**''dir?', 70, 'mikrometre', 'tr'),
('distance', 'Türkiye''nin deniz kıyısının toplam uzunluğu kaç **km**''dir?', 8333, 'km', 'tr'),
('distance', 'Mariana Çukuru''nun derinliği kaç **m**''dir?', 11034, 'm', 'tr'),
('distance', 'Nil Nehri''nin uzunluğu kaç **km**''dir?', 6650, 'km', 'tr'),
('distance', 'Bir futbol sahasının uzunluğu kaç **m**''dir?', 105, 'm', 'tr'),
('distance', 'Uluslararası Uzay İstasyonu''nun yörünge yüksekliği kaç **km**''dir?', 408, 'km', 'tr'),
('distance', 'Tokyo''dan New York''a uçuş mesafesi kaç **km**''dir?', 10838, 'km', 'tr'),
('distance', 'Çin Seddi''nin toplam uzunluğu kaç **km**''dir?', 21196, 'km', 'tr'),
('distance', 'Bir DNA sarmalının çapı kaç **nanometre**''dir?', 2, 'nanometre', 'tr'),
('distance', 'Türkiye''nin doğu-batı uzunluğu kaç **km**''dir?', 1600, 'km', 'tr'),

-- SCALE (20)
('scale', 'Bir fil kaç **kg** ağırlığındadır?', 4000, 'kg', 'tr'),
('scale', 'Bir litre suyun kütlesi kaç **gram**''dır?', 1000, 'gram', 'tr'),
('scale', 'Dünya''nın kütlesi kaç **kg**''dır? (bilimsel gösterim: 6×10^24)', 6000000000000000000000000, 'kg', 'tr'),
('scale', 'Bir erkek aslanın ortalama ağırlığı kaç **kg**''dır?', 190, 'kg', 'tr'),
('scale', 'Dünyadaki toplam insan sayısı kaç **milyar**''dır?', 8, 'milyar', 'tr'),
('scale', 'Bir otomobilin ortalama ağırlığı kaç **kg**''dır?', 1400, 'kg', 'tr'),
('scale', 'Türkiye''nin nüfusu kaç **milyon**''dur?', 85, 'milyon', 'tr'),
('scale', 'Bir bal arısının ağırlığı kaç **miligram**''dır?', 90, 'miligram', 'tr'),
('scale', 'Bir uçak gemisinin ağırlığı kaç **ton**''dur?', 100000, 'ton', 'tr'),
('scale', 'Dünya''daki toplam ağaç sayısı kaç **milyar**''dır?', 3000, 'milyar', 'tr'),
('scale', 'Bir golf topunun ağırlığı kaç **gram**''dır?', 46, 'gram', 'tr'),
('scale', 'Türkiye''de yıllık üretilen çay miktarı kaç **ton**''dur?', 280000, 'ton', 'tr'),
('scale', 'Bir balinanın dili kaç **ton**''dur?', 3, 'ton', 'tr'),
('scale', 'Dünyada her gün tüketilen kahve miktarı kaç **milyon fincan**''dır?', 2250, 'milyon fincan', 'tr'),
('scale', 'Bir kırmızı kan hücresinin çapı kaç **mikrometre**''dir?', 8, 'mikrometre', 'tr'),
('scale', 'Bir Boeing 747''nin boş ağırlığı kaç **ton**''dur?', 178, 'ton', 'tr'),
('scale', 'Dünya''da her yıl üretilen plastik miktarı kaç **milyon ton**''dur?', 400, 'milyon ton', 'tr'),
('scale', 'Bir insan beyninin ağırlığı kaç **gram**''dır?', 1400, 'gram', 'tr'),
('scale', 'Dünyanın en büyük hayvanı mavi balinanın ağırlığı kaç **ton**''dur?', 150, 'ton', 'tr'),
('scale', 'İstanbul''un nüfusu kaç **milyon**''dur?', 15, 'milyon', 'tr'),

-- SPACE (20)
('space', 'Türkiye''nin yüzölçümü kaç **km²**''dir?', 783356, 'km²', 'tr'),
('space', 'Dünya''nın yüzey alanı kaç **milyon km²**''dir?', 510, 'milyon km²', 'tr'),
('space', 'Rusya''nın yüzölçümü kaç **milyon km²**''dir?', 17, 'milyon km²', 'tr'),
('space', 'Bir futbol sahasının alanı kaç **m²**''dir?', 7140, 'm²', 'tr'),
('space', 'Büyük Okyanus''un alanı kaç **milyon km²**''dir?', 165, 'milyon km²', 'tr'),
('space', 'Amazon Ormanı''nın alanı kaç **milyon km²**''dir?', 5, 'milyon km²', 'tr'),
('space', 'Ortalama bir dairenin alanı kaç **m²**''dir?', 90, 'm²', 'tr'),
('space', 'Antarktika''nın alanı kaç **milyon km²**''dir?', 14, 'milyon km²', 'tr'),
('space', 'Bir A4 kağıdının alanı kaç **cm²**''dir?', 623, 'cm²', 'tr'),
('space', 'Sahra Çölü''nün alanı kaç **milyon km²**''dir?', 9, 'milyon km²', 'tr'),
('space', 'İstanbul''un yüzölçümü kaç **km²**''dir?', 5461, 'km²', 'tr'),
('space', 'Dünyanın toplam kara yüzeyinin alanı kaç **milyon km²**''dir?', 149, 'milyon km²', 'tr'),
('space', 'Ortalama bir insan akciğerinin toplam iç yüzey alanı kaç **m²**''dir?', 70, 'm²', 'tr'),
('space', 'Ay''ın yüzey alanı kaç **milyon km²**''dir?', 38, 'milyon km²', 'tr'),
('space', 'Türkiye''deki orman alanı kaç **milyon hektar**''dır?', 22, 'milyon hektar', 'tr'),
('space', 'Bir tenis kortunun alanı kaç **m²**''dir?', 261, 'm²', 'tr'),
('space', 'Kanada''nın yüzölçümü kaç **milyon km²**''dir?', 10, 'milyon km²', 'tr'),
('space', 'Bir insan hücresinin ortalama hacmi kaç **pikolitre**''dir?', 4, 'pikolitre', 'tr'),
('space', 'Dünya''nın toplam okyanus hacmi kaç **milyon km³**''dür?', 1335, 'milyon km³', 'tr'),
('space', 'Olimpik yüzme havuzunun hacmi kaç **m³**''tür?', 2500, 'm³', 'tr'),

-- TIME (20)
('time', 'Evrenin yaşı kaç **milyar yıl**''dır?', 14, 'milyar yıl', 'tr'),
('time', 'Dünya''nın yaşı kaç **milyar yıl**''dır?', 4, 'milyar yıl', 'tr'),
('time', 'Işığın Ay''dan Dünya''ya gelmesi kaç **saniye** sürer?', 1, 'saniye', 'tr'),
('time', 'Bir insan kalbi günde kaç **kez** atar?', 100000, 'kez', 'tr'),
('time', 'Işığın Güneş''ten Dünya''ya gelmesi kaç **dakika** sürer?', 8, 'dakika', 'tr'),
('time', 'Ortalama bir insanın uyku süresi yaşam boyunca kaç **yıl**''dır?', 26, 'yıl', 'tr'),
('time', 'Bir saniyede kaç **milisaniye** vardır?', 1000, 'milisaniye', 'tr'),
('time', 'T-Rex''lerin soyu kaç **milyon yıl** önce tükendi?', 66, 'milyon yıl', 'tr'),
('distance', 'Bir insan saçı bir ayda kaç **mm** uzar?', 15, 'mm', 'tr'),
('time', 'Dünya''nın Güneş etrafında bir tam tur atması kaç **gün** sürer?', 365, 'gün', 'tr'),
('time', 'Osmanlı İmparatorluğu kaç **yıl** sürdü?', 623, 'yıl', 'tr'),
('time', 'İlk modern olimpiyatlar kaç **yıl** önce düzenlendi?', 128, 'yıl', 'tr'),
('time', 'Bir çelik köprünün ortalama ömrü kaç **yıl**''dır?', 75, 'yıl', 'tr'),
('time', 'Işığın Güneş''ten en yakın yıldıza (Proxima Centauri) ulaşması kaç **yıl** sürer?', 4, 'yıl', 'tr'),
('time', 'Bir insanın göz kırpması kaç **milisaniye** sürer?', 150, 'milisaniye', 'tr'),
('time', 'İnternetin kamuya açılması kaç **yıl** önce gerçekleşti?', 35, 'yıl', 'tr'),
('time', 'Dünya''nın kendi ekseni etrafında bir tam tur atması kaç **saat** sürer?', 24, 'saat', 'tr'),
('time', 'Bir müzik CD''sinin maksimum süresi kaç **dakika**''dır?', 74, 'dakika', 'tr'),
('time', 'Türkiye Cumhuriyeti kaç **yıl** önce kuruldu?', 101, 'yıl', 'tr'),
('time', 'Ortalama bir köpeğin ömrü kaç **yıl**''dır?', 12, 'yıl', 'tr'),

-- HUMAN (20)
('human', 'Bir insan vücudunda kaç **kemik** vardır?', 206, 'kemik', 'tr'),
('human', 'Ortalama bir insanın vücudunda kaç **litre** kan vardır?', 5, 'litre', 'tr'),
('human', 'Bir insan vücudunda kaç **trilyon** hücre vardır?', 37, 'trilyon', 'tr'),
('human', 'Ortalama insan yürüyüş hızı kaç **km/saat**''tir?', 5, 'km/saat', 'tr'),
('human', 'Bir insan günde ortalama kaç **kelime** konuşur?', 16000, 'kelime', 'tr'),
('human', 'İnsan vücudunun yüzde kaçı **su**''dan oluşur?', 60, '%', 'tr'),
('human', 'Ortalama bir insanın kafasında kaç **saç teli** vardır?', 100000, 'saç teli', 'tr'),
('human', 'Bir insan günde ortalama kaç **kalori** yakar?', 2000, 'kalori', 'tr'),
('human', 'Ortalama erkek el sıkma kuvveti kaç **kg**''dır?', 46, 'kg', 'tr'),
('human', 'Bir insan burnu kaç farklı **kokuyu** ayırt edebilir?', 1000000, 'koku', 'tr'),
('human', 'Ortalama insan koşu hızı kaç **km/saat**''tir?', 15, 'km/saat', 'tr'),
('human', 'Bir insanın yaşam boyunca ürettiği tükürük miktarı kaç **litre**''dir?', 25000, 'litre', 'tr'),
('human', 'İnsan gözünün ayırt edebildiği renk sayısı kaç **milyon**''dur?', 10, 'milyon', 'tr'),
('human', 'Ortalama insan beyninin işlem hızı kaç **milyon bit/saniye**''dir?', 120, 'milyon bit/saniye', 'tr'),
('human', 'Bir insanın deri yüzey alanı kaç **m²**''dir?', 2, 'm²', 'tr'),
('human', 'Ortalama bir insan günde kaç **adım** atar?', 8000, 'adım', 'tr'),
('human', 'Dünya genelinde kaç **milyon** kişi sol elini kullanır?', 700, 'milyon', 'tr'),
('human', 'Bir insanın ömrü boyunca aldığı nefes sayısı kaç **milyon**''dur?', 600, 'milyon', 'tr'),
('human', 'Ortalama insan reaksiyon süresi kaç **milisaniye**''dir?', 250, 'milisaniye', 'tr'),
('human', 'İnsan vücudundaki toplam damar uzunluğu kaç **km**''dir?', 100000, 'km', 'tr');

-- Seed question_stats for all questions
INSERT INTO question_stats (question_id, answer_count, answers)
SELECT id, 0, '{}'
FROM questions
ON CONFLICT (question_id) DO NOTHING;
